# Site settings
title: "Recording sujae's code"
author: "sujae Jang"
description: "제가 작성한 코드를 기록하는 곳 입니다."
keywords: "Software Engineering,Programming, ect.."

baseurl: ""
url: "https://sujaes.github.io"

Instagram_username: jsujaes
github_username: sujaes
e-mail : sujaes@naver.com

simple_search: http://google.com/search
markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title/
